# Generated by Django 5.0.6 on 2024-08-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('status', models.TextField()),
                ('detalhes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comercializacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.TextField()),
                ('ano', models.IntegerField()),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=20)),
                ('atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atualizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Exportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.TextField()),
                ('pais', models.TextField()),
                ('ano', models.IntegerField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_dolares', models.DecimalField(decimal_places=2, max_digits=20)),
                ('atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atualizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.TextField()),
                ('pais', models.TextField()),
                ('ano', models.IntegerField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_dolares', models.DecimalField(decimal_places=2, max_digits=20)),
                ('atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atualizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.TextField()),
                ('cultivar', models.TextField()),
                ('ano', models.IntegerField()),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=20)),
                ('atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atualizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.TextField()),
                ('ano', models.IntegerField()),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=20)),
                ('atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atualizacao')),
            ],
        ),
    ]
